
server:
  port: 8082
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411
    sender:
      type: web
  application:
    name: payment-service