
server:
  port: 8081
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411
    sender:
      type: web
  application:
    name: order-service
  sleuth:
    async:
      enabled: true
    sampler:
      probability: 1.0  